baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

################################# Menu Section ########################################

                                         ## Wines ##             
[menu]
[[menu.nav]]
  identifier = 'wines'
  name = 'Wines'
  url = '/wines/'
  weight = 5
  [menu.nav.params]
    rel = 'external'
[[menu.nav]]
  name = '2020 Vintage'
  url = '/wines/2020'
  weight = 10
  parent = 'wines'
  [menu.nav.params]
    rel = 'external'
[[menu.nav]]
  name = '2019 Vintage'
  url = '/wines/2019'
  weight = 20
  parent = 'wines'
  [menu.nav.params]
    rel = 'external'    
[[menu.nav]]
  name = '2018 Vintage'
  url = '/wines/2018'
  weight = 30
  parent = 'wines'
  [menu.nav.params]
    rel = 'external'    
[[menu.nav]]
  name = '2017 Vintage'
  url = '/wines/2017'
  weight = 40
  parent = 'wines'
  [menu.nav.params]
    rel = 'external' 
[[menu.nav]]
  name = '2016 Vintage'
  url = '/wines/2016'
  weight = 50
  parent = 'wines'  
  [menu.nav.params]
    rel = 'external'
[[menu.nav]]
  name = '2015 Vintage'
  url = '/wines/2015'
  weight = 60
  parent = 'wines'
  [menu.nav.params]
    rel = 'external'
[[menu.nav]]
  name = '2014 Vintage'
  url = '/wines/2014'
  weight = 70
  parent = 'wines'
  [menu.nav.params]
    rel = 'external'
[[menu.nav]]
  name = '2013 Vintage'
  url = '/wines/2013'
  weight = 80
  parent = 'wines'
  [menu.nav.params]
    rel = 'external'
[[menu.nav]]
  name = '2012 Vintage'
  url = '/wines/2012'
  weight = 90
  parent = 'wines'
  [menu.nav.params]
    rel = 'external'
[[menu.nav]]
  name = '2011 Vintage'
  url = 'https://wines.gaeliccemeteryvineyard.com/2011'
  weight = 100
  parent = 'wines'
  [menu.nav.params]
    rel = 'external'
[[menu.nav]]
  name = '2010 Vintage'
  url = '/wines/2010'
  weight = 110
  parent = 'wines'
  [menu.nav.params]
    rel = 'external'
[[menu.nav]]
  name = '2009 Vintage'
  url = '/wines/2009'
  weight = 120
  parent = 'wines'
  [menu.nav.params]
    rel = 'external'
[[menu.nav]]
  name = '2008 Vintage'
  url = '/wines/2008'
  weight = 130
  parent = 'wines'
  [menu.nav.params]
    rel = 'external'
[[menu.nav]]
  name = '2007 Vintage'
  url = '/wines/2007'
  weight = 140
  parent = 'wines'
  [menu.nav.params]
    rel = 'external'


                                           ## Purchase ##
[[menu.nav]]
  identifier = 'purchase'
  name = 'Purchase'
  url = 'https://purchase.gaeliccemeteryvineyard.com/'
  weight = 200
   [menu.nav.params]
    rel = 'external'   
[[menu.nav]]
  identifier = 'bynow'
  name = 'By Now'
  url = 'https://purchase.gaeliccemeteryvineyard.com/'
  weight = 210
  parent = 'purchase'
  [menu.nav.params]
    rel = 'external'                                            
[[menu.nav]]
  identifier = 'myaccount'
  name = 'My Account'
  url = 'https://purchase.gaeliccemeteryvineyard.com/my-account/'
  weight = 220
  parent = 'purchase'
  [menu.nav.params]
    rel = 'external'
[[menu.nav]]
  identifier = 'policies'
  name = 'Policies'
  url = 'https://purchase.gaeliccemeteryvineyard.com/policies/'
  weight = 230
  parent = 'purchase'
  [menu.nav.params]
    rel = 'external'    
[[menu.nav]]
  identifier = 'distributors'
  name = 'Distributors'
  url = 'https://purchase.gaeliccemeteryvineyard.com/distributors/'
  weight = 240
  parent = 'purchase'
  [menu.nav.params]
    rel = 'external'    
[[menu.nav]]
  identifier = 'wholesalers'
  name = 'Wholesalers'
  url = 'https://purchase.gaeliccemeteryvineyard.com/wholesalers/'
  weight = 250
  parent = 'purchase'
  [menu.nav.params]
    rel = 'external'    
[[menu.nav]]
  identifier = 'retailers'
  name = 'Retailers'
  url = 'https://purchase.gaeliccemeteryvineyard.com/retailers/'
  weight = 260
  parent = 'purchase'
  [menu.nav.params]
    rel = 'external'   

                 ###      Wine Club       ##

[[menu.nav]]
  identifier = 'wineclub'
  name = 'Wineclub'
  url = 'https://purchase.gaeliccemeteryvineyard.com/wine-club/'
  weight = 270
  [menu.nav.params]
    rel = 'external'   

      #########################             Brands       ####################
      
[[menu.nav]]
  identifier = 'brands'
  name = 'Brands'
  url = '/brands/'
  weight = 280
   [menu.nav.params]
    rel = 'external'           
[[menu.nav]]
  identifier = 'pirathon'
  name = 'Pirathon'
  url = '/brands/pirathon/'
  weight = 290
  parent = 'brands'
  [menu.nav.params]
    rel = 'external'   
[[menu.nav]]
  identifier = 'gaelic-cemetery'
  name = 'Gaelic Cemetry Vineyard'
  url = '/brands/gaelic-cemetery-vineyard/'
  weight = 300
  parent = 'brands'
  [menu.nav.params]
    rel = 'external'   
[[menu.nav]]
  identifier = 'lanzerac-country'
  name = 'Lanzerac Country Eestate'
  url = '/brands/lanzerac-country-estate/'
  weight = 310
  parent = 'brands'
  [menu.nav.params]
    rel = 'external'   

                                        ##  Preoperties  ##

[[menu.nav]]
  identifier = 'properties'
  name = 'Properties'
  url = '/properties/'
  weight = 320
   [menu.nav.params]
    rel = 'external'                                        
[[menu.nav]]
  identifier = 'pirathon-winery'
  name = 'Pirathon Winery'
  url = '/properties/pirathon-winery'
  weight = 330
  parent = 'properties'
  [menu.nav.params]
    rel = 'external'         
[[menu.nav]]
  identifier = 'pirathon-vineyard'
  name = 'Pirathon Vineyard'
  url = '/properties/pirathon-vineyard'
  weight = 340
  parent = 'properties'
  [menu.nav.params]
    rel = 'external'
[[menu.nav]]
  identifier = 'gaelic-cemetery-vineyard'
  name = 'Gaelic Cemetry Vineyard'
  url = '/properties/gaelic-cemetery-vineyard'
  weight = 350
  parent = 'properties'
  [menu.nav.params]
    rel = 'external'
[[menu.nav]]
  identifier = 'lanzerac-country-estate'
  name = 'Lanzerac Country Eestate'
  url = '/properties/lanzerac-country-estate'
  weight = 360
  parent = 'properties'
  [menu.nav.params]
    rel = 'external'

                            ##   About   ##

[[menu.nav]]
  identifier = 'about'
  name = 'About'
  url = '/about/'
  weight = 370
   [menu.nav.params]
    rel = 'external'  
[[menu.nav]]
  identifier = 'about-us'
  name = 'About Us'
  url = '/about/'
  weight = 380
  parent = 'about'
  [menu.nav.params]
    rel = 'external'
[[menu.nav]]
  identifier = 'contact'
  name = 'Contact'
  url = '/about/contact'
  weight = 390
  parent = 'about'
  [menu.nav.params]
    rel = 'external'    
[[menu.nav]]
  identifier = 'blog'
  name = 'Blog'
  url = 'https://blog.gaeliccemeteryvineyard.com/'
  weight = 400
  parent = 'about'
  [menu.nav.params]
    rel = 'external'  
[[menu.nav]]
  identifier = 'legal'
  name = 'Legal'
  url = '/about/legal'
  weight = 410
  parent = 'about'
  [menu.nav.params]
    rel = 'external'        
